// src/context/usenotification.ts
import { useContext } from "react";
import NotificationContext from "./notificationContext"; // This should work if it's default export

export interface Notification {
  id: number;
  title: string;
  message: string;
  is_read: boolean;
  created_at: string;
}

export const useNotification = () => {
  const context = useContext(NotificationContext);
  if (!context) {
    throw new Error("useNotification must be used within a NotificationProvider");
  }
  return context;
};

// ✅ Add useSystemNotifications hook to the same file
export const useSystemNotifications = () => {
  const { addNotification } = useNotification();

  const notifySystemAlert = (message: string): void => {
    addNotification("System Alert", message);
  };

  const notifyReservationUpdate = (reservationId: string, status: string): void => {
    addNotification(
      "Reservation Update",
      `Your reservation #${reservationId} has been ${status}.`
    );
  };

  const notifyNewSample = (sampleId: string, sampleType: string): void => {
    addNotification(
      "New Sample Added",
      `A new ${sampleType} sample (ID: ${sampleId}) has been added to the system.`
    );
  };

  const notifySampleStatus = (sampleId: string, oldStatus: string, newStatus: string): void => {
    addNotification(
      "Sample Status Updated",
      `Sample ${sampleId} status changed from ${oldStatus} to ${newStatus}.`
    );
  };

  const notifyReportGenerated = (reportId: string, reportType: string, generatedBy: string): void => {
    addNotification(
      "Report Generated",
      `A new ${reportType} report (ID: ${reportId}) has been generated by ${generatedBy}.`
    );
  };

  const notifyReportUpdated = (reportId: string, updatedBy: string): void => {
    addNotification(
      "Report Updated",
      `Report ${reportId} has been updated by ${updatedBy}.`
    );
  };

  return {
    notifySystemAlert,
    notifyReservationUpdate,
    notifyNewSample,
    notifySampleStatus,
    notifyReportGenerated,
    notifyReportUpdated
  };
};